ktVersion=2.3.20
shadowJarVersion=9.6.0
easylibPluginVersion=1.3.2
easylibVersion=4.7.6
neigeItemsVersion=1.15.113
spigotApiVersion=1.18.2-R0.1-SNAPSHOT
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true
kotlin.parallel.tasks.in.project=true
group=com.xbaimiao.shoppro
version=1.6.3
